In [1]:
import pandas as pd
import siconfipy

In [63]:
import fastparquet

Geramos a base _infos_ para ter a informação dos códigos de UG conforme a base utiliza.

In [ ]:
infos = siconfipy.get_info()
infos = infos[infos.esfera == 'E']
infos

_ = list(infos.cod_ibge)

,cod_ibge,ente,capital,regiao,uf,esfera,exercicio,populacao,cnpj
1719,17,Tocantins,0,NO,BR,E,2025,1584306,01786029000103
5436,11,Rondônia,0,NO,BR,E,2025,1616379,00394585000171
5437,12,Acre,0,NO,BR,E,2025,829780,63606479000124
5438,13,Amazonas,0,NO,BR,E,2025,3952262,04312369000190
5439,14,Roraima,0,NO,BR,E,2025,634805,84012012000126
5440,15,Pará,0,NO,BR,E,2025,8442962,05054861000176
5441,16,Amapá,0,NO,BR,E,2025,774268,00394577000125
5442,21,Maranhão,0,NE,BR,E,2025,6800605,06354468000160
5443,22,Piauí,0,NE,BR,E,2025,3270174,06553481000149
5444,23,Ceará,0,NE,BR,E,2025,8936431,07954480000179
5445,24,Rio Grande do Norte,0,NE,BR,E,2025,3303953,08241739000105
5446,25,Paraíba,0,NE,BR,E,2025,4030961,08761124000100
5447,26,Pernambuco,0,NE,BR,E,2025,9051113,10571982000125
5448,27,Alagoas,0,NE,BR,E,2025,3125254,12200176000176
5449,28,Sergipe,0,NE,BR,E,2025,2211868,13128798000101
5450,29,Bahia,0,NE,BR,E,2025,14659023,13937032000160
5451,31,Minas Gerais,0,SE,BR,E,2025,20732660,18715615000160
5452,32,Espírito Santo,0,SE,BR,E,2025,3975100,27080530000143
5453,33,Rio de Janeiro,0,SE,BR,E,2025,16615526,42498600000171
5454,35,São Paulo,0,SE,BR,E,2025,46024937,46379400000150
5455,41,Paraná,0,SU,BR,E,2025,11835379,76416940000128
5456,42,Santa Catarina,0,SU,BR,E,2025,7762154,82951229000176
5457,43,Rio Grande do Sul,0,SU,BR,E,2025,11088065,87934675000196
5458,50,Mato Grosso do Sul,0,CO,BR,E,2025,2833742,15412257000128
5459,51,Mato Grosso,0,CO,BR,E,2025,3784239,03507415000144
5460,52,Goiás,0,CO,BR,E,2025,6950976,01409580000138

Determinamos uma variável placeholder pra segurar as informações dos códigos, pra gerar a base das contas anuais para todas as unidades federativas.

In [54]:
df = siconfipy.get_annual_acc(year = [2013, 2014, 2015, 2016, 2017, 2018, 2019,2020, 2021, 2022],
                     cod = _,
                     annex = "DCA-Anexo I-E")

In [123]:
df = pd.read_parquet(path = 'dados_siconfi.parquet')

In [124]:
df = df.drop(['populacao', 'instituicao'], axis = 1)

In [110]:
df_teste = df_teste[(df_teste.exercicio == 2022)]

In [112]:
df_teste = df_teste[(df_teste.anexo == 'DCA-Anexo I-E')]

In [116]:
df_teste = df_teste[(df_teste.coluna == 'Despesas Pagas')]

In [120]:
df_teste = df_teste[(df_teste.conta.isin(['12 - Educação',
                                         '12.363 - Ensino Profissional',
                                         '12.364 - Ensino Superior',
                                         '12.366 - Educação de Jovens e Adultos',
                                         '12.368 - Educação Básica',
                                         '12.122 - Administração Geral',
                                         'FU12 - Demais Subfunções']))]

In [121]:
df_teste.conta.unique()

array(['12 - Educação', '12.363 - Ensino Profissional',
       '12.364 - Ensino Superior',
       '12.366 - Educação de Jovens e Adultos',
       '12.368 - Educação Básica', '12.122 - Administração Geral',
       'FU12 - Demais Subfunções'], dtype=object)

In [122]:
df_teste.to_excel('dados_siconfi_teste.xlsx', index = False)

In [126]:
df = df[(df.anexo.isin(['Anexo I-E', 'DCA-Anexo I-E']))
        &
        (df.conta.isin(['12 - Educação',
                        '12.363 - Ensino Profissional',
                        '12.364 - Ensino Superior',
                        '12.366 - Educação de Jovens e Adultos',
                        '12.368 - Educação Básica',
                        '12.122 - Administração Geral',
                        'FU12 - Demais Subfunções']))
        &
        (df.coluna == 'Despesas Pagas')]

In [127]:
df.to_excel('dados_siconfi_educacao.xlsx', index = False)